# Generated by Django 5.1.3 on 2024-11-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreeableness',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='emotional_stablility',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='social_orientation',
            field=models.CharField(choices=[('Extrovert', 'Extrovert'), ('Ambivert', 'Ambivert'), ('Introvert', 'Introvert')], default='Extrovert', max_length=50),
            preserve_default=False,
        ),
    ]
