# Generated by Django 5.1.3 on 2024-11-14 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserChoosedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boots', models.ManyToManyField(to='tinder.boots')),
                ('chestplates', models.ManyToManyField(to='tinder.chestplate')),
                ('helmets', models.ManyToManyField(to='tinder.helmet')),
                ('leggings', models.ManyToManyField(to='tinder.legging')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
