# Generated by Django 5.1.3 on 2024-11-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_userinventory_user_userchooseditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchooseditem',
            name='boots',
        ),
        migrations.RemoveField(
            model_name='userchooseditem',
            name='chestplates',
        ),
        migrations.RemoveField(
            model_name='userchooseditem',
            name='helmets',
        ),
        migrations.RemoveField(
            model_name='userchooseditem',
            name='leggings',
        ),
        migrations.AddField(
            model_name='userchooseditem',
            name='boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tinder.boots'),
        ),
        migrations.AddField(
            model_name='userchooseditem',
            name='chestplates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tinder.chestplate'),
        ),
        migrations.AddField(
            model_name='userchooseditem',
            name='helmets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tinder.helmet'),
        ),
        migrations.AddField(
            model_name='userchooseditem',
            name='leggings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tinder.legging'),
        ),
    ]
