# Generated by Django 5.1.3 on 2024-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0003_remove_userchooseditem_boots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='boots',
            field=models.ManyToManyField(blank=True, null=True, to='tinder.boots'),
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='chestplates',
            field=models.ManyToManyField(blank=True, null=True, to='tinder.chestplate'),
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='helmets',
            field=models.ManyToManyField(blank=True, null=True, to='tinder.helmet'),
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='leggings',
            field=models.ManyToManyField(blank=True, null=True, to='tinder.legging'),
        ),
    ]
