# Generated by Django 5.1.3 on 2024-11-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0006_rename_chestplates_userchooseditem_chestplate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchooseditem',
            old_name='boots',
            new_name='boot',
        ),
    ]
