# Generated by Django 5.1.3 on 2024-11-14 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0008_questnode_questedge_nodeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questedge',
            name='to_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_node_to', to='tinder.questnode'),
        ),
    ]
